const kanjiList = [  
  { kanji: "人", romaji: "hiro", meaning: "person" },
  { kanji: "スリランカ人", romaji: "sururankajin", meaning: "sri lankan" },
  { kanji: "一人", romaji: "hitori", meaning: "one person" },
  { kanji: "二人", romaji: "futari", meaning: "two persons" },
  { kanji: "三人", romaji: "sannin", meaning: "three persons" },
  { kanji: "男の人", romaji: "otokonohito", meaning: "man" },
  { kanji: "女の人", romaji: "onnanohito", meaning: "woman" },
  { kanji: "こい人", romaji: "koibito", meaning: "lover" },
  { kanji: "木", romaji: "ki", meaning: "tree" },
  { kanji: "木曜日", romaji: "mokuyoubi", meaning: "thursday" },
  { kanji: "川", romaji: "kawa", meaning: "river" },
  { kanji: "山川", romaji: "sansen", meaning: "mountains and rivers" },
  { kanji: "川さき", romaji: "kawasaki", meaning: "river cape" },
  { kanji: "山", romaji: "yama", meaning: "mountain" },
  { kanji: "山みち", romaji: "yamamichi", meaning: "mountain road" },
  { kanji: "ふじ山", romaji: "fujisen", meaning: "mountain fuji" },
  { kanji: "火山", romaji: "kazan", meaning: "volcano" },
  { kanji: "女の子", romaji: "onnanoko", meaning: "girl" },
  { kanji: "男の子", romaji: "otokonoko", meaning: "boy" },
  { kanji: "女子", romaji: "joshi", meaning: "girl" },
  { kanji: "男子", romaji: "danshi", meaning: "boy" },
  { kanji: "日", romaji: "hi", meaning: "sun/day" },
  { kanji: "休みの日", romaji: "yasuminohi", meaning: "day off" },
  { kanji: "いち日", romaji: "ichinichi", meaning: "one day" },
  { kanji: "毎日", romaji: "mainichi", meaning: "every day" },
  { kanji: "休日", romaji: "kyuujitsu", meaning: "holiday" },
  { kanji: "たんじょ日", romaji: "tanjoubi", meaning: "birthday" },
  { kanji: "本", romaji: "hon", meaning: "book" },
  { kanji: "日本", romaji: "nihon", meaning: "japan" },
  { kanji: "本とう", romaji: "hontou", meaning: "true" },
  { kanji: "本てん", romaji: "honten", meaning: "head office" },
  { kanji: "二本", romaji: "nihon", meaning: "two things (cylindrical)" },
  { kanji: "山本", romaji: "yamamoto", meaning: "mountain base" },
  { kanji: "雨", romaji: "ame", meaning: "rain" },
  { kanji: "雨水", romaji: "amamizu", meaning: "rain water" },
  { kanji: "一", romaji: "ichi", meaning: "one" },
  { kanji: "一つ", romaji: "hitotsu", meaning: "one thing" },
  { kanji: "一日", romaji: "tsuitachi", meaning: "first day of month" },
  { kanji: "一本", romaji: "ippon", meaning: "one thing (cylindrical)" },
  { kanji: "二", romaji: "ni", meaning: "two" },
  { kanji: "二日", romaji: "futsuka", meaning: "2nd day of month" },
  { kanji: "二だい", romaji: "nidai", meaning: "two things (machine)" },
  { kanji: "三", romaji: "san", meaning: "three" },
  { kanji: "三日", romaji: "mikka", meaning: "3rd day of month" },
  { kanji: "四", romaji: "yon", meaning: "four" },
  { kanji: "四日", romaji: "yokka", meaning: "4th day of month" },
  { kanji: "四き", romaji: "shiki", meaning: "four season" },
  { kanji: "十", romaji: "juu", meaning: "ten" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
  { kanji: "", romaji: "", meaning: "" },
];
